inherit_from: configs/500_experiment_boxibox/base_config.yaml
mapping:
  hash_size: 12
  keyframe_every: 10
  map_every: 5
  first_iters: 500
tracking:
  iter: 20
  best: true
grid:
  voxel_color: 0.04
  voxel_sdf: 0.01
training:
  smooth_weight: 0.001
  smooth_pts: 64
  n_samples_d: 96
mesh:
  voxel_eval: 0.05
  voxel_final: 0.03
data:
  datadir: data/box_model
  trainskip: 1
  output: output/box_experiments
  exp_name: boxibox_experiment_0046
