inherit_from: configs/500_experiment_boxibox/base_config.yaml
mapping:
  hash_size: 16
  keyframe_every: 5
  map_every: 10
  first_iters: 1000
tracking:
  iter: 20
  best: true
grid:
  voxel_color: 0.04
  voxel_sdf: 0.01
training:
  smooth_weight: 1.0e-05
  smooth_pts: 32
  n_samples_d: 96
mesh:
  voxel_eval: 0.05
  voxel_final: 0.02
data:
  datadir: data/box_model
  trainskip: 1
  output: output/box_experiments
  exp_name: boxibox_experiment_0003
