inherit_from: configs/500_experiment_boxibox/base_config.yaml
mapping:
  hash_size: 12
  keyframe_every: 5
  map_every: 10
  first_iters: 1000
tracking:
  iter: 20
  best: true
grid:
  voxel_color: 0.04
  voxel_sdf: 0.04
training:
  smooth_weight: 1.0e-08
  smooth_pts: 64
  n_samples_d: 64
mesh:
  voxel_eval: 0.05
  voxel_final: 0.015
data:
  datadir: data/box_model
  trainskip: 1
  output: output/box_experiments
  exp_name: boxibox_experiment_0097
