inherit_from: configs/500_experiment_boxibox/base_config.yaml
mapping:
  hash_size: 19
  keyframe_every: 10
  map_every: 10
  first_iters: 1000
tracking:
  iter: 10
  best: true
grid:
  voxel_color: 0.08
  voxel_sdf: 0.04
training:
  smooth_weight: 1.0e-06
  smooth_pts: 32
  n_samples_d: 96
mesh:
  voxel_eval: 0.05
  voxel_final: 0.03
data:
  datadir: data/box_model
  trainskip: 1
  output: output/box_experiments
  exp_name: boxibox_experiment_0067
