inherit_from: configs/nerf/iphone_version.yaml

mapping:
  bound: [[-10.0, 10.0],[-10.0, 10.0],[-10.0, 10.0]]
  marching_cubes_bound: [[-10.0, 10.0],[-10.0, 10.0],[-10.0, 10.0]]

data:
  datadir: data/SyntheticData/chair
  trainskip: 1
  output: output/SyntheticData/chair
  exp_name: chair_demo
